---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curator
  namespace: logging
spec:
  schedule: 1 15 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curator
              image: ${docker_image}:${tag}
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/curator/
              securityContext:
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
