variable "environment" {}
variable "region" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "whitelist_security_groups" {}
variable "tags" {}
variable "activemq_engine_version" {}
variable "activemq_storage_type" {}
variable "activemq_host_instance_type" {}
variable "apply_immediately" {}
variable "auto_minor_version_upgrade" {}
variable "activemq_publicly_accessible" {}
variable "activemq_username" {}