variable "name" {}
variable "region" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "whitelist_security_groups" {}
variable "ingress_whitelist_ips" {}
variable "egress_whitelist_ips" {}
variable "tags" {}
variable "engine_version" {}
variable "storage_type" {}
variable "instance_type" {}
variable "apply_immediately" {}
variable "auto_minor_version_upgrade" {}
variable "publicly_accessible" {}
variable "username" {}