client:
  host: ${OPENSEARCH_ENDPOINT}
  port: 443
  use_ssl: false
  ssl_no_validate: true
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  retry:
    count: 5
    back-off: 0.2
actions:
  - name: create_snapshot
    description: "Make backup of all indices"
    options:
      repository: s3-snapshot
      name: snapshot
      continue_if_exception: False
      ignore_unavailable: False
      include_global_state: True
      partial: False
      disable_action: False
      wait_for_completion: True
    filters:
      index_pattern: "filebeat*"
      direction: older
      unit: days
      count: 1
  - name: delete_indices
    description: "Clean up ES by deleting custom defined old indices"
    options:
      disable_action: False
      continue_if_exception: False
    filters:
      index_pattern: "filebeat*"
      direction: older
      unit: days
      count: ${DELETE_OLD_INDICES_COUNT}
  - name: delete_monitoring_objects
    description: "Delete all Monitoring Objects's JSONs older than the given date "
    options:
      repository: s3-snapshot
      disable_action: False
      continue_if_exception: False
    filters:
      unit: days
      count: ${DELETE_OLD_INDICES_COUNT}
