apiVersion: batch/v1
kind: CronJob
metadata:
  name: curator
  namespace: logging
spec:
  schedule: 1 15 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curator
              image: ${DOCKER_IMAGE}
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/curator/
          volumes:
            - name: config-volume
              configMap:
                name: ${CONFIG_MAP}
          restartPolicy: OnFailure
