docker_registry: 150399859526.dkr.ecr.us-west-2.amazonaws.com
customer: "baton"
domain: ""
subdomain_suffix: ""
env: {}
health_endpoint: "/health"
image_tag: 1.0.0
targetPort: 8080
port: 8080
url_prefix: ""
volumes: []
mounts: []
security_context: true