#do not remove this comment (added here to maintain yaml formating ) 
  enabled: true
  config:
    global:
      slack_api_url: ${slack_web_hook}
    route:
      receiver: default
      group_by:
      - alertname
      - cluster
      - service
      - job
      continue: false
      routes:
      - receiver: "empty"
        match:
          alertname: Watchdog
        continue: true
      - receiver: 'gchat'
        match:
          severity: warning
        continue: true
      - receiver: 'slack'
        match:
          severity: warning
        continue: true
      - receiver: 'pagerduty'
        match:
          severity: critical
        continue: true
    receivers:
      - name: "empty"
      - name: gchat
        webhook_configs:
        - send_resolved: true
          http_config:
            follow_redirects: true
          url: ${gchat_lambda_url}
          max_alerts: 0
      - name: default
        slack_configs:
        - send_resolved: false
          http_config:
            follow_redirects: true
          channel: ${slack_channel_name}
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
           {{ range .Alerts -}}
           *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
           *Description:* {{ .Annotations.description }}
           *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
           {{ end }}
      - name: pagerduty
        pagerduty_configs:
        - service_key: ${pagerduty_key}
          send_resolved: true
      - name: slack 
        slack_configs:
        - send_resolved: true
          channel: ${slack_channel_name}
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
           {{ range .Alerts -}}
           *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
           *Description:* {{ .Annotations.description }}
           *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
           {{ end }}
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "efs"
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: ${alert_manager_volume_size}