image:
  registry: registry.k8s.io
  repository: kube-state-metrics/kube-state-metrics
  tag: v${image_version}
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 250Mi
  requests:
    cpu: 10m
    memory: 190Mi
