apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      application: {{ .Release.Name }}
  template:
    metadata:
      labels:
        application: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.docker_registry }}/baton/{{ .Values.customer }}/{{ .Release.Name }}:{{ .Values.image_tag }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- if ( .Values.security_context ) }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          {{- end }}
          imagePullPolicy: Always
          {{- if and ( .Values.health_endpoint ) ( .Values.url_prefix ) }}
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: {{ .Values.url_prefix }}{{ .Values.health_endpoint }}
              port: {{ .Values.targetPort }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          {{- end }}
          volumeMounts:
{{ toYaml .Values.mounts | indent 12 }}      
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
      volumes: 
{{ toYaml .Values.volumes | indent 8}}