apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    application: {{ .Release.Name }}
  ports:
  - port: {{ .Values.port }}
    name: http
    targetPort: {{ .Values.targetPort }}