variable "env" {}
variable "name" {}
variable "mounts" {}
variable "volumes" {}
variable "customer" {}
variable "namespace" {}
variable "image_tag" {}
variable "url_prefix" {}
variable "target_port" {}
variable "domain_name" {}
variable "health_endpoint" {}
variable "subdomain_suffix" {}