lbc_addon_version      = "1.6.0"
istio_version          = "1.20.0"
slack_web_hook         = "https://hooks.slack.com/services/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"
slack_channel_name     = "terraform-test-alerts"
siem_storage_s3_bucket = "eks-auto-vpc-flow-logs"

environment                        = "aksh"
pagerduty_key                      = "8d81b91f50e54dc09a2400fbeb019c84"
custom_alerts                      = []
opensearch_endpoint                = ""
opensearch_username                = "master"
opensearch_password                = "ns(i)61uYMB)l-IC"
domain_name                        = "batonsystems.com"
grafana_role_arn                   = ""
acm_certificate_arn                = ""
efs_id                             = ""
cloudflare_api_token               = "jPvl-qF3HMK1VkY2s6JK7tLx3PeN3uVsbwJDerLl"
enable_cluster_autoscaler          = true
create_dns_records                 = false
enable_siem                        = false
enable_config_server               = true //this
bitbucket_key_secrets_manager_name = "config-server-key"
config_repo_url                    = "git@bitbucket.org:ubixi/config-repo.git"
config_server_image_tag            = 56 //this
enable_sftp                        = true
sftp_namespace                     = "sftp"
sftp_username                      = "myuser"
