apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ${namespace}-gateway
  namespace: ${namespace}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts: ${hosts}
    port:
      name: http
      number: 80
      protocol: HTTP