variable "name" {}
variable "tags" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "rabbitmq_sg" {}
variable "rabbitmq_endpoint" {}
variable "whitelist_ips" {}
variable "public_certificate_arn" {}
variable "rabbitmq_cluster_mode" {}