variable "opensearch_password" {}
variable "opensearch_username" {}
variable "opensearch_endpoint" {}
variable "delete_indices_from_es" {}
variable "docker_image_arn" {}
variable "create_s3_bucket_for_curator" {}
variable "environment" {}
variable "domain_name" {}
variable "region" {}
