variable "region" {}
variable "vendor" {}
variable "dependency" {}
variable "domain_name" {}
variable "environment" {}
variable "opensearch_password" {}
variable "opensearch_username" {}
variable "opensearch_endpoint" {}
variable "delete_indices_from_es" {}
variable "create_s3_bucket_for_curator" {}